(in-package :annil)

(defun autoscale-params-from-matrix (train-set)
  ;; get means and norms from train set
  (let ((dim0 (dim0 train-set))
	(dim1 (dim1 train-set)))
    (let ((col (make-matrix dim0))
	  (means (make-matrix dim1))
	  (norms (make-matrix dim1)))
      (dotimes (j dim1)
	(col train-set j col)
	(setf (aref means j) (mean col))
	;; *2 is a kludge
	;; real way of scaling: Xs=X*inv(diag(std(X)))
	(setf (aref norms j) (* (e-norm col) 2)))
      (list means norms))))

(defun autoscale-params (train-set)
  (patterns-dispatch (train-set)
		     (error "Autoscaling doesn't make sence for single pattern")
		     (error "Autoscaling doesn't make sence for single pattern")
		     (autoscale-params-from-matrix train-set)
		     (autoscale-params-from-matrix (first train-set))
		     (autoscale-params-from-matrix (convert-patterns-to-matrix train-set))
		     (autoscale-params-from-matrix (first (convert-patterns-to-matrix train-set)))))

(defun autoscale-input (input means norms)
  (m/ (m- input means) norms))

(defun undo-autoscale-input (input means norms)
  (m+ (m* input norms) means))

(defun autoscale (patterns means norms)
  (patterns-dispatch (patterns)
		     (autoscale-input patterns means norms)
		     (autoscale-input (first patterns) means norms)
		     (dotimes (i (dim0 patterns) patterns)
		       (setf (row patterns i)
			     (autoscale-input (row patterns i) means norms)))
		     (dotimes (i (dim0 (first patterns)) patterns)
		       (setf (row (first patterns) i)
			     (autoscale-input (row (first patterns) i) means norms)))
		     (map nil #'(lambda (i) (autoscale-input i means norms)) patterns)
		     (map nil #'(lambda (p) (autoscale-input (first p) means norms)) patterns))
  patterns)

(defun undo-autoscale (patterns means norms)
  (patterns-dispatch (patterns)
		     (undo-autoscale-input patterns means norms)
		     (undo-autoscale-input (first patterns) means norms)
		     (dotimes (i (dim0 patterns) patterns)
		       (setf (row patterns i)
			     (undo-autoscale-input (row patterns i) means norms)))
		     (dotimes (i (dim0 (first patterns)) patterns)
		       (setf (row (first patterns) i)
			     (undo-autoscale-input (row (first patterns) i) means norms)))
		     (map nil #'(lambda (i) (undo-autoscale-input i means norms)) patterns)
		     (map nil #'(lambda (p) (undo-autoscale-input (first p) means norms)) patterns))
  patterns)
